services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/KoyaAndy18/malunes-ecom.git
    region: oregon
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: YOUR_APP_KEY_HERE
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_RENDER_DATABASE_HOST
      - key: DB_DATABASE
        value: YOUR_DATABASE_NAME
      - key: DB_USERNAME
        value: YOUR_DATABASE_USER
      - key: DB_PASSWORD
        value: YOUR_DATABASE_PASSWORD
    autoDeploy: true
